import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/AntonSC.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const inter = localFont({
  src: "./fonts/inter.ttf",
  weight: "100 900",
});

const antonSC = localFont({
  src: "./fonts/AntonSC.ttf",
  weight: "100 900",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${inter.className} antialiased`}
      >
        {/* <Navbar/> */}
        {children}
      </body>
    </html>
  );
}
